### ISSUE TITLE
elasticsearch 8 support

### ISSUE THREAD

**Issue by Morgy93** [ddev/ddev-elasticsearch#15]
Currently it seems not possible to run elasticsearch 8:

1. `mkdir ddev`
2. `cd ddev`
3. `ddev config` press Enter for everything
4. `ddev get ddev/ddev-elasticsearch`
5. Open `.ddev/docker-compose.elasticsearch.yaml`
6. Change line 6 to `image: elasticsearch:8.5.3`
7. `ddev start`
8. See error:
```
Failed to start ddev: container(s) failed to become healthy before their configured timeout or in 120 seconds.
This might be a problem with the healthcheck and not a functional problem.
(container /ddev-ddev-elasticsearch is unhealthy: [ ... just some datetimes ...]) 
```

Any idea?

**Comment by rfay** [comment]
Did you try `ddev logs -s elasticsearch` ?

Is it important to use elasticsearch:8?

**Comment by Morgy93** [comment]
> Did you try `ddev logs -s elasticsearch` ?

Great idea, there is one error I can see:

`"log.level":"ERROR", "message":"exception during geoip databases update"`

Interestingly everything else after that is successfull:

`"log.level": "INFO",  "current.health":"GREEN","message":"Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[.geoip_databases][0]]])."`

`"log.level": "INFO", "message":"successfully loaded geoip database file [GeoLite2-Country.mmdb]"`+ ASN + City

> Is it important to use elasticsearch:8?

Well, I *could* use 7.17 as well, but since latest stable Magento Commerce on-premises 2.4.6-p3 supports 8.5, I'd like to use that one instead.
Source: https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html
For the next major version which is currently in beta only 8.7 is supported.

**Comment by rfay** [comment]
Don't you have to add on geoip somehow to use it? Thanks for working on this. Maybe @cmuench has some thoughts. 

One thing that's happening with various add-ons is an initiative to change the underlying version.

Note that you can do it here with a `docker-compose.elasticsearch-extra.yaml` that will override the version, so you don't have to edit the actual add-on files.

Also, isn't Magento actually mostly insisting on opensearch these days?

**Comment by cmuench** [comment]
Sadly I have not personaly upgraded to ES8 in any project.
ES8 is supported in the latest Magento 2.4.6.

There are some hints here: https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/prepare/prerequisites.html?lang=en#upgrade-elasticsearch

**Comment by cmuench** [comment]
I can reproduce the issue:

```
Failed to start ddev-es8: container(s) failed to become healthy before their configured timeout or in 120 seconds. This might be a problem with the healthcheck and not a functional problem. (container /ddev-ddev-es8-elasticsearch is unhealthy: [{2023-10-20 10:09:05.825819392 +0200 CEST 2023-10-20 10:09:05.948366668 +0200 CEST 52 } {2023-10-20 10:09:35.962975144 +0200 CEST 2023-10-20 10:09:36.040488574 +0200 CEST 52 } {2023-10-20 10:10:06.062972601 +0200 CEST 2023-10-20 10:10:06.136560755 +0200 CEST 52 }]) 
```

**Comment by cmuench** [comment]
Problem is the healthcheck. If I remove the healthcheck from `.ddev/docker-compose.elasticsearch.yaml` it's starting.

This seems to work:

```yaml
services:
  elasticsearch:
    container_name: ddev-${DDEV_SITENAME}-elasticsearch
    hostname: ${DDEV_SITENAME}-elasticsearch
    image: elasticsearch:8.5.3
    expose:
      - "9200"
      - "9300"
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=9200:9200
      - HTTPS_EXPOSE=9201:9200
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
      - ".:/mnt/ddev_config"
    #healthcheck:
    #  test: ["CMD-SHELL", "curl --fail -s localhost:9200"]

volumes:
  elasticsearch:
```
